# Build stage
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

# Copiar o JAR compilado
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

# Variáveis de ambiente para dev
ENV SPRING_PROFILES_ACTIVE=dev \
    SPRING_RABBITMQ_HOST=rabbitmq \
    SPRING_RABBITMQ_PORT=5672 \
    SPRING_RABBITMQ_USERNAME=admin \
    SPRING_RABBITMQ_PASSWORD=admin

ENTRYPOINT ["java", "-jar", "/app/app.jar"]