spring.datasource.url=jdbc:mysql://localhost:3306/brinkcalcados_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.sql.init.continue-on-error=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.jdbc.datasource.init=DEBUG

# Substitua pelo valor abaixo (ou um similar de 32+ caracteres)
jwt.secret=essa-e-uma-chave-muito-longa-e-segura-para-o-ambiente-de-desenvolvimento-2026
api.gateway.url=${API_GATEWAY_URL:http://localhost:8080}