spring.application.name=crud-proj-v1

server.error.include-message=always
server.error.include-binding-errors=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# RabbitMQ (já está perfeito)
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin}

# JWT
jwt.validity=3600000
jwt.secret=SEU_SECRET